[workspace]
members = [
    "programs/hello-solana",
    "programs/escrow",
    "programs/counter",
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello-solana = "VT4xECAJb32gNheoLxYJnJksW4WxTgYW4v6A2Y2sYYv"
escrow = "5K8XyZfcTir7V57zbYrYRrLZmYMKkc7jjX6wGz1TT8eD"
counter = "GHiMm9tjXW9Ynh927EgovMgp5cA9hpbxPYpEYq6hyo2p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/taegi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
