[workspace]
members = [
    "programs/contracts-for-cards",
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts_for_cards = "VT4xECAJb32gNheoLxYJnJksW4WxTgYW4v6A2Y2sYYv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/taegi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
